layout_spectrum: 0.3965959
typography_spectrum: 0.1925937
color:
  saturation: 0.3632859
  lightness: 0.1872625
  brandStrength: 0.4631054
  rhythmicContrast: 0.02226395
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: jjdelatorre
